name: pdf_scanner
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_localizations:
    sdk: flutter

  go_router: ^14.2.7
  easy_localization: ^3.0.7+1
  device_preview: ^1.2.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.6.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.17
  # device_preview: ^1.2.0
  json_annotation: ^4.9.0
  logger: any #for logging purpose
  fpdart: ^1.1.1
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  easy_debounce: ^2.0.3

  custom_refresh_indicator: ^4.0.1
  share_plus: ^11.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  shimmer: ^3.0.0
  loader_overlay: ^5.0.0
  keyboard_actions: ^4.2.0
  intl: 0.19.0
  path_provider: ^2.1.5
  flutter_popup: ^3.3.4

  permission_handler: ^11.4.0
  #error
  talker: any
  talker_flutter: ^4.5.2
  talker_riverpod_logger: ^4.7.1

  #UI
  flash: ^3.1.1

  google_fonts: ^6.2.1
  # slang: ^4.6.0
  # slang_flutter: ^4.6.0

  flutter_native_splash: ^2.4.5
  pro_image_editor: 9.0.0
  cunning_document_scanner: ^1.2.3
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  path: ^1.9.1
  uuid: ^4.0.0
  pdf_render: ^1.4.12
  image_picker: ^1.1.0

  vector_graphics: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ">=2.3.0 <4.0.0"
  flutter_lints: ^5.0.0
  freezed: ^2.4.5
  json_serializable: ^6.6.2
  riverpod_generator: ^2.4.0
  change_app_package_name: ^1.3.0
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  # slang_build_runner: ^4.6.0
  drift_dev: ^2.26.1

flutter:
  # generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/splash/
    - assets/translations/

flutter_gen:
  output: lib/generated/assets/

  integrations:
    image: true
    flutter_svg: true
    lottie: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
